name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t Dockerfile

      - name: Login to Docker Hub (or another container registry)
        run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin

      - name: Push Docker image to registry
        run: docker push Dockerfile

      - name: Deploy to Heroku
        run: |
          heroku container:login
          heroku container:release web -a <heroku-app-name>
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
