name: CI/CD for Ruby on Rails

on:
  push:
    branches:
      - satyabhavsar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          docker build -t fitxt .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub (or another container registry)
        run: echo Faizankhaji@786 | docker login -u khajifaizanali@tamu.edu --password-stdin

      - name: Push Docker image to registry
        run: docker push fitxtd

      - name: Deploy to Heroku
        run: |
          heroku container:login
          heroku container:release web -a fitxtd
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
