name: CI/CD for Ruby on Rails

on:
  push:
    branches:
      - satyabhavsar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build and test
        run: |
          docker build -t fitxt .
      - name: List Docker images
        run: docker images
        
      - name: Login to Docker Hub
        run: docker login -u khajifaizanali@tamu.edu -p Faizankhaji@786

      - name: Push Docker image to registry
        run: docker tag fitxt khajifaizanali/fitxt
      - name: Push Docker image to registry
        run: docker push khajifaizanali/fitxt

      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fitxtd" #Must be unique in Heroku
          heroku_email: "khajifaizanali@tamu.edu"
          stack: "container"
