name: CI/CD for Ruby on Rails

on:
  push:
    branches:
      - satyabhavsar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          docker build -t fitxt .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        run: docker login -u khajifaizanali@tamu.edu -p Faizankhaji@786

      - name: Push Docker image to registry
        run: docker push fitxt

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: fitxtd
