name: CI/CD for Ruby on Rails

on:
  push:
    branches:
      - satyabhavsar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7 # Specify your Ruby version

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: |
          bundle install
          docker build -t fitxt .
          docker run fitxt bundle exec rspec # Replace with your test command

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          build_dir: .
